### ISSUE TITLE
/usr/local/bin/init.sh: no such file or directory

### ISSUE THREAD

**Issue by lracicot** [jareds/docker-taskd#1]
I ran a totally fresh setup and got this error when I ran the first docker run command:

```bash
docker run --volumes-from taskddata --name taskd --rm taskd /usr/local/bin/init.sh lracicot lracicot 0.0.0.0
container_linux.go:247: starting container process caused "exec: \"/usr/local/bin/init.sh\": stat /usr/local/bin/init.sh: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/local/bin/init.sh\": stat /usr/local/bin/init.sh: no such file or directory".
```

Running on Docker version 17.05.0-ce, build 89658be

**Comment by jareds** [comment]
Please update to the latest code and try building from scratch including the --no-cache flag. The source code repository path changed a while ago so I had to update the dockerfile to point at the proper location. I was successfully able to execute your command with the latest commit building from scratch. I'm running docker 17.0.9.0-ce.
Note 0.0.0.0 is not the IP address you want to use, you need to use a routable IP address. While your command runs successfully with 0.0.0.0 as the IP I suspect you will have issues configuring a task client.

**Comment by jareds** [comment]
Closing do to no follow up.
